config/routes.rb
Rajawali::Application.routes.draw do

  root :to => 'home#index'

   match ':controller(/:action(/:id))(.:format)'

   match '/home' => 'home#index', :as => :home

   match '/who_i_am' => 'who_iam#index', :as => :who_iam

   match '/career' => 'career#index', :as => :career

   match '/product' => 'product#index', :as => :product

   match '/client' => 'client#index', :as => :client

   match '/contact' => 'contact#index', :as => :contact

   match ':controller(/:action(/:id))(.:format)'

   match 'home/index' => 'user#index', :as => :home

   match 'career/index' => 'career#index', :as => :career
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/career_controller.rb
class CareerController < ApplicationController
  def index
  end
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end
end

app/controllers/who_iam_controller.rb
class WhoIamController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/career_helper.rb
module CareerHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/who_iam_helper.rb
module WhoIamHelper
end

app/views/career/index.html.erb
<h1>Career#index</h1>
<p>Find me in app/views/career/index.html.erb</p>

app/views/client/index.html.erb
<h1>Client#index</h1>
<p>Find me in app/views/client/index.html.erb</p>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rajawali</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="menu">
	<%= link_to "Home", home_path%>
	<%= link_to "Who I am", who_iam_path%>
	<%= link_to "Product", product_path%>
	<%= link_to "Client", client_path%>
	<%= link_to "Career", career_path%>
	<%= link_to "Contact", contact_path%>
</div>

<%= yield %>

</body>
</html>

app/views/product/index.html.erb
<h1>Product#index</h1>
<p>Find me in app/views/product/index.html.erb</p>

app/views/who_iam/index.html.erb
<h1>WhoIam#index</h1>
<p>Find me in app/views/who_iam/index.html.erb</p>